### ISSUE TITLE
Ajuda com criação de modelos e/ou intuição

### ISSUE THREAD

**Issue by GabrieldeAS** [igormq/speech2text#1]
Estive lidando com o toolkit Kaldi e API Vosk e gostaria de saber se esse é o caminho mais adequado. Não sou especialista em ASR ou mesmo pós-graduando da área, mas gostaria de mais intuição para criação de modelos. Um dos problemas que eu tive com o toolkit Kaldi é que seguindo o tutorial em http://kaldi-asr.org/doc/graph_recipe_test.html eu não consigo gerar um grafo para decode. Também não sei sobre as implicações/acoplamento com o modelo acústico e seu treinamento.

Você tem algum material que pode compartilhar, alguma sabedoria ou contato? Obrigado.

**Comment by igormq** [comment]
Olá @GabrieldeAS , o pessoal usa muito o toolkit do Kaldi, mas eu particularmente acho bem difícil adaptar ele para novos modelos e/ou testar coisas teóricas.

Te recomendaria tentar frameworks mais fáceis, como o NEMO ASR ou EspNet. 

Qualquer coisa, só me enviar uma outra mensagem!

Abraços.
